In [1]:
!pip install requests beautifulsoup4 pandas

Requirement already satisfied: requests in c:\users\merli\anaconda3\lib\site-packages (2.32.5)
Requirement already satisfied: beautifulsoup4 in c:\users\merli\anaconda3\lib\site-packages (4.13.5)
Requirement already satisfied: pandas in c:\users\merli\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\merli\anaconda3\lib\site-packages (from requests) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\merli\anaconda3\lib\site-packages (from requests) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\merli\anaconda3\lib\site-packages (from requests) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\merli\anaconda3\lib\site-packages (from requests) (2025.11.12)
Requirement already satisfied: soupsieve>1.2 in c:\users\merli\anaconda3\lib\site-packages (from beautifulsoup4) (2.5)
Requirement already satisfied: typing-extensions>=4.0.0 in c:\users\merli\anaconda3\lib\site-packages (from beautifulsoup4) (4.15.0)
Requirement already satisfied: numpy>=1.26.0 in c:\users\merli\anaconda3\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\merli\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\merli\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\merli\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\merli\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [3]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

In [4]:
url = "https://books.toscrape.com/"

response = requests.get(url)

print(response.status_code)

200

In [5]:
soup = BeautifulSoup(response.text, "html.parser")

In [6]:
books = soup.find_all("article", class_="product_pod")

print("Number of books:", len(books))

Number of books: 20

In [7]:
first_book = books[0]

title = first_book.h3.a["title"]
price = first_book.find("p", class_="price_color").text
availability = first_book.find(
    "p",
    class_="instock availability"
).text.strip()

print("Title:", title)
print("Price:", price)
print("Availability:", availability)

Title: A Light in the Attic
Price: Â£51.77
Availability: In stock

In [8]:
data = []

for book in books:
    title = book.h3.a["title"]
    price = book.find("p", class_="price_color").text
    availability = book.find(
        "p",
        class_="instock availability"
    ).text.strip()

    data.append([title, price, availability])

print("Books Extracted:", len(data))

Books Extracted: 20

In [9]:
df = pd.DataFrame(
    data,
    columns=["Title", "Price", "Availability"]
)

df.head()

                                   Title    Price Availability
0                   A Light in the Attic  Â£51.77     In stock
1                     Tipping the Velvet  Â£53.74     In stock
2                             Soumission  Â£50.10     In stock
3                          Sharp Objects  Â£47.82     In stock
4  Sapiens: A Brief History of Humankind  Â£54.23     In stock

In [10]:
df.to_csv("books.csv", index=False)

print("CSV Saved Successfully!")

CSV Saved Successfully!

In [11]:
import os

print(os.listdir())

['.ipynb_checkpoints', 'books.csv', 'Untitled.ipynb', 'WebScraping.ipynb']

In [12]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
from time import sleep

base_url = "https://books.toscrape.com/catalogue/page-{}.html"

data = []

for page in range(1, 51):

    url = base_url.format(page)

    response = requests.get(url)

    soup = BeautifulSoup(response.text, "html.parser")

    books = soup.find_all("article", class_="product_pod")

    for book in books:

        title = book.h3.a["title"]

        price = book.find(
            "p",
            class_="price_color"
        ).text

        availability = book.find(
            "p",
            class_="instock availability"
        ).text.strip()

        data.append([
            title,
            price,
            availability
        ])

    print(f"Page {page} scraped")

    sleep(1)

df = pd.DataFrame(
    data,
    columns=[
        "Title",
        "Price",
        "Availability"
    ]
)

print("Total Books:", len(df))

df.head()

Page 1 scraped
Page 2 scraped
Page 3 scraped
Page 4 scraped
Page 5 scraped
Page 6 scraped
Page 7 scraped
Page 8 scraped
Page 9 scraped
Page 10 scraped
Page 11 scraped
Page 12 scraped
Page 13 scraped
Page 14 scraped
Page 15 scraped
Page 16 scraped
Page 17 scraped
Page 18 scraped
Page 19 scraped
Page 20 scraped
Page 21 scraped
Page 22 scraped
Page 23 scraped
Page 24 scraped
Page 25 scraped
Page 26 scraped
Page 27 scraped
Page 28 scraped
Page 29 scraped
Page 30 scraped
Page 31 scraped
Page 32 scraped
Page 33 scraped
Page 34 scraped
Page 35 scraped
Page 36 scraped
Page 37 scraped
Page 38 scraped
Page 39 scraped
Page 40 scraped
Page 41 scraped
Page 42 scraped
Page 43 scraped
Page 44 scraped
Page 45 scraped
Page 46 scraped
Page 47 scraped
Page 48 scraped
Page 49 scraped
Page 50 scraped
Total Books: 1000

                                   Title    Price Availability
0                   A Light in the Attic  Â£51.77     In stock
1                     Tipping the Velvet  Â£53.74     In stock
2                             Soumission  Â£50.10     In stock
3                          Sharp Objects  Â£47.82     In stock
4  Sapiens: A Brief History of Humankind  Â£54.23     In stock

In [13]:
df.to_csv(
    "books_1000.csv",
    index=False
)

print("Dataset Saved Successfully!")

Dataset Saved Successfully!

In [14]:
df.shape

(1000, 3)

In [16]:
df.head()

                                   Title    Price Availability
0                   A Light in the Attic  Â£51.77     In stock
1                     Tipping the Velvet  Â£53.74     In stock
2                             Soumission  Â£50.10     In stock
3                          Sharp Objects  Â£47.82     In stock
4  Sapiens: A Brief History of Humankind  Â£54.23     In stock

In [17]:
df.dtypes

Title           object
Price           object
Availability    object
dtype: object

In [18]:
print(df["Price"].head())

0    Â£51.77
1    Â£53.74
2    Â£50.10
3    Â£47.82
4    Â£54.23
Name: Price, dtype: object